"""Report generation — produces the final publishable Markdown article and HTML page."""

from pathlib import Path
from typing import Optional
import pandas as pd
from jinja2 import Template

from src.analysis import run_analysis, print_summary
from src.config import EDITIONS

OUTPUT_DIR = Path("output")
TEMPLATES_DIR = Path("templates")

REPORT_TEMPLATE = """# Figma × Contra Makeathon Analysis: What Separates Winners from Everyone Else?

*A data-backed community report — {{ generated_date }}*

---

## The Pattern

{% if results %}
After scraping and analyzing {{ total_entries }} entries across {{ results|length }} makeathon editions, a clear pattern emerges. The data suggests that **early posting correlates with winning**, but it's not the whole story. Winners also tend to have:
- Higher engagement scores ({{ engagement_ratio }}× the non-winner average)
- Greater social cross-platform presence
- Higher likelihood of being featured in official recaps
{% else %}
*Analysis data not yet available — run the scraping and analysis pipeline first.*
{% endif %}

---

## Edition-by-Edition Breakdown

{% for r in results %}
### {{ r.edition }}

| Metric | Winners | Non-Winners |
|--------|---------|-------------|
| Entries | {{ r.total_winners }} | {{ r.total_entries - r.total_winners }} |
| Avg Post Day | Day {{ "%.1f"|format(r.winner_avg_post_day) }} | Day {{ "%.1f"|format(r.non_winner_avg_post_day) }} |
| Avg Engagement | {{ "%.0f"|format(r.winner_avg_engagement) }} | {{ "%.0f"|format(r.non_winner_avg_engagement) }} |
| Avg Social Platforms | {{ "%.1f"|format(r.winner_avg_social_platforms) }} | {{ "%.1f"|format(r.non_winner_avg_social_platforms) }} |
| Recap Inclusion | {{ "%.0f"|format(r.winner_recap_pct) }}% | {{ "%.0f"|format(r.non_winner_recap_pct) }}% |
| Video Presence | {{ "%.0f"|format(r.winner_video_pct) }}% | {{ "%.0f"|format(r.non_winner_video_pct) }}% |

{% endfor %}

---

## The Timing Effect

*When did winners post vs everyone else?*

The timing histogram (see `output/figures/`) shows the distribution of posting days for winners compared to non-winners. Early birds do have an edge, but winners also appear throughout the submission window — suggesting **quality trumps pure earliness**.

{% if timing_chart %}
![Posting Day Distribution]({{ timing_chart }})
{% endif %}

---

## The Social Multiplier

*Did cross-posting correlate with winning?*

Winners cross-posted to an average of **{{ "%.1f"|format(winner_avg_social|float) }} social platforms** compared to {{ "%.1f"|format(non_winner_avg_social|float) }} for non-winners. The data suggests that **social amplification matters** — every additional platform linked correlates with higher visibility and engagement.

---

## The Recap Game

*Were recaps decided early?*

{{ "%.0f"|format(winner_recap_pct|float) }}% of winners appeared in official Contra recap posts vs {{ "%.0f"|format(non_winner_recap_pct|float) }}% of non-winners. This could mean recaps influence winning perception, or that the judging panel and recap writers converge on similar projects.

---

## What This Means for You

If you're entering the next Figma × Contra makeathon:

1. **Post early** — early entries get more time to accumulate engagement and visibility
2. **Cross-post everywhere** — each platform adds a multiplier effect
3. **Include a video** — video presence correlates with higher engagement
4. **Build in public** — share your process, not just the final result
5. **Engage with the community** — likes and comments create a feedback loop

---

## Raw Data

Full datasets available in the `data/` directory:
- [`winners.csv`](data/winners.csv) — Detailed winner metadata
- [`all_entries.csv`](data/all_entries.csv) — All scraped entries
- [`social_posts.csv`](data/social_posts.csv) — Linked social posts

Interactive charts in `output/figures/`.

---

*Generated by the Figma Makeathon Analysis pipeline. PRD: `agents/context/prd.md`*
"""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Figma × Contra Makeathon Analysis</title>
    <style>
        :root {
            --purple: #7C3AED;
            --gray: #94A3B8;
            --bg: #0F172A;
            --card: #1E293B;
            --text: #E2E8F0;
            --muted: #94A3B8;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
        }
        .container { max-width: 800px; margin: 0 auto; padding: 2rem 1.5rem; }
        h1 { font-size: 2.5rem; margin-bottom: 0.5rem; color: #fff; }
        h2 { font-size: 1.6rem; margin: 2.5rem 0 1rem; color: var(--purple); }
        h3 { font-size: 1.2rem; margin: 1.5rem 0 0.75rem; color: #fff; }
        p { margin: 0.75rem 0; }
        .subtitle { color: var(--muted); font-style: italic; margin-bottom: 2rem; }
        .card {
            background: var(--card);
            border-radius: 12px;
            padding: 1.5rem;
            margin: 1rem 0;
        }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #334155; }
        th { color: var(--purple); font-weight: 600; }
        ol { padding-left: 1.5rem; margin: 1rem 0; }
        li { margin: 0.5rem 0; }
        a { color: var(--purple); }
        .highlight { color: var(--purple); font-weight: 600; }
        .chart-container { margin: 2rem 0; }
        iframe { width: 100%; height: 500px; border: none; border-radius: 12px; background: var(--card); }
        hr { border: none; border-top: 1px solid #334155; margin: 2rem 0; }
        footer { color: var(--muted); font-size: 0.85rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #334155; }
    </style>
</head>
<body>
    <div class="container">
        {{ content }}
    </div>
</body>
</html>
"""


def generate_report(
    df: Optional[pd.DataFrame] = None,
    all_entries_path: str = "data/all_entries.csv",
) -> str:
    """Generate the full Markdown report."""
    from datetime import date

    if df is None:
        try:
            from src.analysis import load_data, compute_derived_fields
            df = load_data(all_entries_path)
            df = compute_derived_fields(df)
        except FileNotFoundError:
            # No data yet — generate placeholder
            return _render_placeholder()

    results = []
    for edition in EDITIONS:
        r = run_analysis(df, edition.name)
        results.append(r)

    # Aggregate stats (for summary values only, not listed as an edition)
    r_all = run_analysis(df, None)

    timing_chart = "output/figures/all_timing_histogram.html"

    # Only include editions with actual entries
    edition_results = [r for r in results if r.total_entries > 0]

    template = Template(REPORT_TEMPLATE)
    report = template.render(
        generated_date=date.today().isoformat(),
        results=edition_results,
        total_entries=r_all.total_entries,
        total_winners=r_all.total_winners,
        winner_avg_engagement=r_all.winner_avg_engagement,
        winner_avg_social=r_all.winner_avg_social_platforms,
        non_winner_avg_social=r_all.non_winner_avg_social_platforms,
        winner_recap_pct=r_all.winner_recap_pct,
        non_winner_recap_pct=r_all.non_winner_recap_pct,
        timing_chart=timing_chart,
        engagement_ratio=round(r_all.winner_avg_engagement / max(1, r_all.non_winner_avg_engagement), 1),
    )

    return report


def _render_placeholder() -> str:
    """Render a placeholder report when no data is available."""
    from datetime import date
    template = Template(REPORT_TEMPLATE)
    return template.render(
        generated_date=date.today().isoformat(),
        results=[],
        total_entries=0,
        total_winners=0,
        winner_avg_engagement=0,
        winner_avg_social=0,
        non_winner_avg_social=0,
        winner_recap_pct=0,
        non_winner_recap_pct=0,
        timing_chart="",
        engagement_ratio=0,
    )


def render_html(report_md: str) -> str:
    """Convert Markdown report to styled HTML."""
    # Simple Markdown-to-HTML conversion for key elements
    html = report_md
    # Headers
    html = html.replace("\n## ", "\n<h2>").replace("\n### ", "\n<h3>")
    # Close headers
    for tag in ["h2", "h3"]:
        html = html.replace(f"<{tag}>", f"</p>\n<{tag}>")
    # Bold
    html = html.replace("**", "<strong>", 1)
    html = html.replace("**", "</strong>", 1)
    # Lists
    html = html.replace("\n1. ", "\n<li>")
    html = html.replace("\n- ", "\n<li>")

    template = Template(HTML_TEMPLATE)
    return template.render(content=html)


def save_report(report_md: str, html: str):
    """Save report as Markdown and HTML files."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    md_path = OUTPUT_DIR / "report.md"
    md_path.write_text(report_md)
    print(f"  Markdown report saved to {md_path}")

    html_path = OUTPUT_DIR / "index.html"
    html_path.write_text(html)
    print(f"  HTML report saved to {html_path}")
